version: 2
project_name: cyanprint
before:
  hooks:
    - bun install --frozen-lockfile
builds:
  - id: cyanprint
    builder: bun
    binary: cyanprint
    main: packages/cli/src/main.ts
    targets:
      - darwin-x64
      - darwin-arm64
      - linux-x64
      - linux-arm64
      - windows-x64
archives:
  - ids: [cyanprint]
    formats: [tar.gz]
checksum:
  name_template: 'checksums.txt'
homebrew_casks:
  - name: cyanprint
    binaries:
      - cyanprint
    homepage: https://cyanprint.dev
    description: CyanPrint v4 local-first template runtime
    repository:
      owner: AtomiCloud
      name: homebrew-tap
      token: '{{ .Env.SCOOP_BREW_TOKEN }}'
scoops:
  - name: cyanprint
    homepage: https://cyanprint.dev
    description: CyanPrint v4 local-first template runtime
    repository:
      owner: AtomiCloud
      name: scoop-bucket
      token: '{{ .Env.SCOOP_BREW_TOKEN }}'
nfpms:
  - id: packages
    package_name: cyanprint
    vendor: AtomiCloud
    homepage: https://cyanprint.dev/
    maintainer: Ernest Ng <kirinnee97@gmail.com>
    description: CyanPrint v4 local-first template runtime
    license: MIT
    ids: [cyanprint]
    meta: false
    formats: [deb, rpm, apk, archlinux]
