import type { ProbeDefinition } from '@cyanprint/contracts';

/**
 * Probes for the `coverage` feature: the committed ledger is genuinely
 * regenerated by the gate, so a stale or edited ledger turns it red.
 */
const definition: ProbeDefinition = {
  contractVersion: 1,
  probes: [
    {
      name: 'baseline-coverage-gate-green',
      description: 'The untouched repo passes its coverage ledger check.',
      kind: 'baseline',
      async run(repo) {
        const result = await repo.exec('bash scripts/coverage-gate.sh');
        if (result.exitCode !== 0) {
          throw new Error(`coverage gate failed on the healthy repo: ${result.stderr}`);
        }
      },
    },
    {
      name: 'edited-ledger-reddens-gate',
      description: 'Hand-editing the coverage ledger must turn the coverage gate red.',
      kind: 'mutation',
      expectedImpact: ['ci'],
      async run(repo) {
        await repo.write('coverage/ledger.txt', '999\n');
        const result = await repo.exec('bash scripts/coverage-gate.sh');
        if (result.exitCode === 0) {
          throw new Error('coverage gate stayed green after the ledger was edited');
        }
      },
    },
  ],
};

export default definition;
