cyanprint: 4
template:
  owner: cyanprint
  name: all-types
  version: local
  source: cyanprint/all-types
answers:
  name: Ernest
  enabled: true
  flavor: vanilla
  toppings:
    - sprinkles
  count: 10
deterministicState: {}
files:
  - path: OUT.md
    sha256: 24c66feab43ea5f9264f4f2d85ec1c818aa7e2744f4cdcb40a04fcfad5cc2b61
    content: |
      name=Ernest
      enabled=true
      flavor=vanilla
      toppings=sprinkles
      count=10
artifacts:
  - kind: template
    owner: cyanprint
    name: all-types
    version: local
    integrity: 9993e7e2c6dab3f19badb30a74ef397cf47c366e4c59d90c1e10c554f0aac54f
  - kind: processor
    owner: cyan
    name: default
    version: local
    integrity: da48e4b5d97f88b8ad37aaeaa284e6c7c33f86848f6eb47be34ec03cde816936
conflicts: []
