import { createHash } from 'node:crypto';
import { lstat, mkdir, readFile, rm, rmdir, stat, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import type { VfsFile } from '@cyanprint/contracts';

export async function readText(path: string): Promise<string> {
  return readFile(path, 'utf8');
}

export async function writeText(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, 'utf8');
}

export async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

export async function remove(path: string): Promise<void> {
  await rm(path, { recursive: true, force: true });
}

export function sha256(content: string | Uint8Array): string {
  return createHash('sha256').update(content).digest('hex');
}

/** Content hash of one VFS file (text or binary) — the single fingerprint formula for file bytes. */
export function fileSha(file: VfsFile): string {
  return sha256(file.bytesBase64 !== undefined ? Buffer.from(file.bytesBase64, 'base64') : (file.content ?? ''));
}

/**
 * Map over items with a bounded number of concurrent workers, preserving input order in the
 * result. A limit <= 1 runs sequentially. Used to run independent test cases in parallel.
 */
export async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let cursor = 0;
  const workerCount = Math.max(1, Math.min(Math.floor(limit) || 1, items.length));
  const worker = async (): Promise<void> => {
    while (true) {
      const index = cursor;
      cursor += 1;
      if (index >= items.length) {
        return;
      }
      results[index] = await fn(items[index] as T, index);
    }
  };
  await Promise.all(Array.from({ length: workerCount }, () => worker()));
  return results;
}

/**
 * Deterministic, locale-independent path ordering (code-unit compare). `localeCompare` depends
 * on the host ICU/locale and can order unicode or mixed-case paths differently across machines,
 * which would produce spurious `.cyan_state.yaml` diffs.
 */
export function comparePaths(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

/** Canonical JSON of a config value: sorted object keys, stable across key insertion order. */
export function stableConfig(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(stableConfig).join(',')}]`;
  }
  if (typeof value === 'object' && value !== null) {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record)
      .sort()
      .map(key => `${JSON.stringify(key)}:${stableConfig(record[key])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

/** Write one VFS file under an output root, creating parent directories for both text and binary. */
export async function writeVfsFile(outDir: string, file: VfsFile): Promise<void> {
  const target = safeJoin(outDir, file.path);
  // `safeJoin` only vets the textual path; the on-disk parents may still be symlinks a user
  // planted, which `mkdir`/`Bun.write`/`writeFile` follow — letting a "clean" merge write escape
  // the project root. A hard-linked target likewise shares its inode with a file outside the
  // tree. Refuse either so output stays inside root.
  await assertRootSafeWrite(outDir, file.path);
  if (file.bytesBase64 !== undefined) {
    await mkdir(dirname(target), { recursive: true });
    await Bun.write(target, Buffer.from(file.bytesBase64, 'base64'));
    return;
  }
  await writeText(target, file.content ?? '');
}

/**
 * Throw if writing `relPath` under `root` would escape the project root through a filesystem link.
 * Two escape mechanisms are refused, both invisible to `safeJoin`'s textual check because
 * `readProjectFiles` is link-blind and reports the merge clean:
 *
 * 1. **Symlink component** — any path component from `root` down to the target (inclusive) being a
 *    symlink. `mkdir`/`Bun.write`/`writeFile` follow it, landing bytes outside the project root.
 * 2. **Hard-linked target** — the final file already existing as a regular file with `nlink > 1`.
 *    Truncating and rewriting it mutates the shared inode, changing every other hard link to it
 *    (potentially one outside the project root). Only the leaf is written, so only its link count
 *    matters — directories legitimately carry `nlink > 1` via their subdirectories.
 * 3. **Special-file target** — the final path already existing as a non-regular file (a FIFO/named
 *    pipe, device, or socket). `Bun.write`/`writeFile` open it instead of creating a durable file,
 *    so generated bytes flow into a pipe reader (silent data loss) or the write blocks forever with
 *    no reader. A safe write target is only a nonexistent leaf or a single-link regular file.
 *
 * Mirrors the artifact-runner's refusal to traverse symlinks (`fs-utils.ts`), keeping the managed
 * tree link-free on both read and write.
 */
export async function assertRootSafeWrite(root: string, relPath: string): Promise<void> {
  const parts = relPath.split(/[\\/]+/).filter(part => part && part !== '.');
  const resolvedRoot = resolve(root);
  let current = resolvedRoot;
  for (let index = 0; index < parts.length; index += 1) {
    current = join(current, parts[index] as string);
    const info = await lstat(current).catch(() => undefined);
    if (!info) {
      continue;
    }
    const at = relative(resolvedRoot, current)
      .split(/[\\/]+/)
      .join('/');
    if (info.isSymbolicLink()) {
      throw new Error(
        `Refusing to write through a symlink inside the project: "${relPath}" ("${at}" is a symlink). ` +
          `Remove the symlink and retry — CyanPrint does not write through symlinks in the managed tree.`,
      );
    }
    if (index === parts.length - 1 && info.isFile() && info.nlink > 1) {
      throw new Error(
        `Refusing to write through a hard link inside the project: "${relPath}" ("${at}" has ${info.nlink} links). ` +
          `Remove the hard link and retry — CyanPrint does not write through hard links in the managed tree.`,
      );
    }
    // Leaf-only: a non-regular, non-directory leaf is a FIFO/device/socket. Opening it with
    // `Bun.write`/`writeFile` redirects generated bytes into it (data loss) or blocks with no
    // reader. A leaf directory is left for the caller's dir→file pruning / natural EISDIR.
    if (index === parts.length - 1 && !info.isFile() && !info.isDirectory()) {
      throw new Error(
        `Refusing to write through a special file inside the project: "${relPath}" ("${at}" is a FIFO, device, or socket). ` +
          `Remove it and retry — CyanPrint only writes regular files in the managed tree.`,
      );
    }
  }
}

/**
 * Throw if deleting `relPath` under `root` would escape the project through a symlinked parent.
 * The write path is guarded by {@link assertRootSafeWrite}; deletion needs the same protection on
 * its own vector: `rm(root/relPath)` follows a symlinked *parent* component and unlinks the target
 * outside the project root (e.g. `assets -> /tmp/outside`, deleting managed `assets/config.txt`
 * removes `/tmp/outside/config.txt`). `readProjectFiles` is link-blind, so such a path can still
 * surface as a clean `merge.deletions` entry. Only parent components are checked — a symlink *leaf*
 * is removed as a link (its target is untouched), which is safe.
 */
export async function assertRootSafeDelete(root: string, relPath: string): Promise<void> {
  const parts = relPath.split(/[\\/]+/).filter(part => part && part !== '.');
  const resolvedRoot = resolve(root);
  let current = resolvedRoot;
  // Parents only: stop before the leaf (`parts.length - 1`).
  for (let index = 0; index < parts.length - 1; index += 1) {
    current = join(current, parts[index] as string);
    const info = await lstat(current).catch(() => undefined);
    if (!info) {
      return;
    }
    if (info.isSymbolicLink()) {
      const at = relative(resolvedRoot, current)
        .split(/[\\/]+/)
        .join('/');
      throw new Error(
        `Refusing to delete through a symlink inside the project: "${relPath}" ("${at}" is a symlink). ` +
          `Remove the symlink and retry — CyanPrint does not delete through symlinks in the managed tree.`,
      );
    }
  }
}

/**
 * Throw if reading `relPath` under `root` would escape the project through a symlink in ANY
 * path component — a symlinked parent OR a symlinked leaf. `readFile`/`read` follow the link
 * transparently, so a leaf `secret -> /etc/passwd` or a parent `assets -> /tmp/outside` reads
 * bytes from outside the managed tree. Unlike {@link assertRootSafeWrite} this checks symlinks
 * only (a hard-linked or single-link regular file is a safe read target), and unlike
 * {@link assertRootSafeDelete} it includes the leaf (following a symlink leaf escapes on read).
 */
export async function assertRootSafeRead(root: string, relPath: string): Promise<void> {
  const parts = relPath.split(/[\\/]+/).filter(part => part && part !== '.');
  const resolvedRoot = resolve(root);
  let current = resolvedRoot;
  for (const part of parts) {
    current = join(current, part);
    const info = await lstat(current).catch(() => undefined);
    if (!info) {
      // A missing component means nothing deeper exists to traverse either.
      return;
    }
    if (info.isSymbolicLink()) {
      const at = relative(resolvedRoot, current)
        .split(/[\\/]+/)
        .join('/');
      throw new Error(
        `Refusing to read through a symlink inside the project: "${relPath}" ("${at}" is a symlink). ` +
          `Remove the symlink and retry — CyanPrint does not read through symlinks in the managed tree.`,
      );
    }
  }
}

/**
 * Remove ancestor directories a deletion emptied, so a path a directory occupied is free
 * for a file write. `rmdir` refuses non-empty directories, so sibling content survives.
 */
export async function pruneEmptyDirs(root: string, deletedPath: string): Promise<void> {
  let current = dirname(deletedPath);
  while (current && current !== '.' && current !== '/') {
    const removed = await rmdir(safeJoin(root, current)).then(
      () => true,
      () => false,
    );
    if (!removed) {
      return;
    }
    current = dirname(current);
  }
}

/** Decode bytes as UTF-8 text; undefined for binary (invalid UTF-8 or embedded NUL). */
export function decodeText(bytes: Uint8Array): string | undefined {
  try {
    const text = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
    return text.includes('\u0000') ? undefined : text;
  } catch {
    return undefined;
  }
}

export function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export function safeJoin(root: string, child: string): string {
  const resolvedRoot = resolve(root);
  const resolved = resolve(root, child);
  const fromRoot = relative(resolvedRoot, resolved);
  if (fromRoot === '..' || fromRoot.startsWith('../') || fromRoot.startsWith('..\\') || isAbsolute(fromRoot)) {
    throw new Error(`Refusing to write outside output directory: ${child}`);
  }
  return resolved;
}
