import type { PluginHelper, PluginInput } from '@cyanprint/sdk';

export async function plugin(input: PluginInput, helper: PluginHelper) {
  // Demonstrate an idempotent command run inside the output directory.
  await helper.exec('echo "Generated by Footer Plugin"');
  const files = await helper.read();
  await helper.write([...files, { path: 'PLUGIN.md', content: '# Plugin output\n\nGenerated by Footer Plugin.\n' }]);
}
