name: cyanprint

on:
  push:
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build, test, and publish
        env:
          CYANPRINT_TOKEN: ${{ secrets.CYANPRINT_TOKEN }}
        run: bash scripts/cyanprint-ci.sh
