import { join } from 'node:path';
import type { Answers, ProbeFeatureIdentity, ProbeManifest, ProbeRunReport, ProbeVerdict } from '@cyanprint/contracts';
import { CyanError, PROBE_CONTRACT_VERSION, ProbeManifestSchema, problem } from '@cyanprint/contracts';
import YAML from 'yaml';
import { createProject } from '../create/create-project';
import { withTempSession } from '../sessions/temp-session';
import { loadTemplateTestCases, readCaseRecord } from '../testing/run-template-tests';
import { unifiedDiff } from '../util/unified-diff';
import { comparePaths, exists, readText, writeText } from '../util';
import { probeKey, type ResolvedFeatureProbes } from './matrix';
import { resolveProbesForTemplate, type ProbeOverrideInput } from './resolve';

/** The committed manifest's filename — always next to cyan.yaml. */
export const PROBE_MANIFEST_FILE = 'probes.yaml';

const MANIFEST_HEADER =
  '# Machine-generated by the CyanPrint probe engine — do not edit.\n' +
  '# Regenerate with the probe manifest generator; drift fails the gates.\n';

/**
 * Derive a template's feature set: the union of features declared by the
 * template's curated test profiles' generations (`cyan.test.yaml` cases run
 * headlessly) — deterministic given the committed answers, so profile/answer
 * changes that alter the feature set are legitimate manifest drift (FR6).
 */
export async function deriveTemplateFeatureSet(templateDir: string): Promise<ProbeFeatureIdentity[]> {
  const cases = await loadTemplateTestCases(templateDir);
  if (cases.length === 0) {
    throw new CyanError(
      problem(
        'validation',
        'probe_manifest_requires_test_profiles',
        `Probe manifest derivation needs curated test profiles: ${templateDir} has no cyan.test.yaml cases. ` +
          'The feature set is the union of the profiles’ generations — add a cyan.test.yaml first.',
        { templateDir },
      ),
    );
  }
  const union = new Map<string, ProbeFeatureIdentity>();
  for (const testCase of cases) {
    const answers = await readCaseRecord<Answers>(testCase.answers, 'answers');
    const deterministicState = await readCaseRecord<Record<string, unknown>>(
      testCase.deterministicState,
      'deterministicState',
    );
    const features = await withTempSession(async session => {
      const result = await createProject({
        template: templateDir,
        outDir: join(session.path, 'out'),
        headless: true,
        answers,
        deterministicState,
      });
      return result.features;
    });
    for (const feature of features) {
      union.set(`${feature.template}\u0000${feature.name}`, feature);
    }
  }
  return [...union.values()].sort(
    (left, right) => comparePaths(left.template, right.template) || comparePaths(left.name, right.name),
  );
}

/**
 * Generate a template's `probes.yaml` content (FR6): contract version, every
 * feature under per-template identity, its probes with mandatory descriptions,
 * and each probe's resolution origin — the audit trail that answers "what runs,
 * and where did it come from?" (including, for overrides, what was displaced).
 */
export async function generateProbeManifest(
  templateDir: string,
  options?: { overrides?: ProbeOverrideInput[]; workspaceRoot?: string },
): Promise<ProbeManifest> {
  const features = await deriveTemplateFeatureSet(templateDir);
  const resolved = await resolveProbesForTemplate({
    templateDir,
    features,
    overrides: options?.overrides,
    workspaceRoot: options?.workspaceRoot,
  });
  return buildProbeManifest(resolved);
}

/** The manifest shape from an already-resolved feature set. */
export function buildProbeManifest(resolved: ResolvedFeatureProbes[]): ProbeManifest {
  return ProbeManifestSchema.parse({
    contractVersion: PROBE_CONTRACT_VERSION,
    features: resolved.map(feature => ({
      template: feature.feature.template,
      name: feature.feature.name,
      probes: feature.probes.map(entry => ({
        name: entry.probe.name,
        description: entry.probe.description,
        kind: entry.probe.kind,
        origin: entry.origin,
      })),
    })),
  });
}

/**
 * The run report is the manifest shape with exactly one verdict attached to
 * every probe (FR7); a probe the execution somehow left unjudged is `broken`,
 * never silently omitted.
 */
export function buildProbeRunReport(
  resolved: ResolvedFeatureProbes[],
  verdicts: Map<string, ProbeVerdict>,
): ProbeRunReport {
  return {
    contractVersion: PROBE_CONTRACT_VERSION,
    features: resolved.map(feature => ({
      template: feature.feature.template,
      name: feature.feature.name,
      probes: feature.probes.map(entry => ({
        name: entry.probe.name,
        description: entry.probe.description,
        kind: entry.probe.kind,
        origin: entry.origin,
        verdict: verdicts.get(probeKey(feature.feature, entry.probe.name)) ?? 'broken',
      })),
    })),
  };
}

/** Deterministic serialized form — the exact bytes committed as probes.yaml. */
export function renderProbeManifest(manifest: ProbeManifest): string {
  return MANIFEST_HEADER + YAML.stringify(manifest);
}

/** Generate and write a template's committed probes.yaml next to its cyan.yaml. */
export async function writeProbeManifest(
  templateDir: string,
  options?: { overrides?: ProbeOverrideInput[]; workspaceRoot?: string },
): Promise<ProbeManifest> {
  const manifest = await generateProbeManifest(templateDir, options);
  await writeText(join(templateDir, PROBE_MANIFEST_FILE), renderProbeManifest(manifest));
  return manifest;
}

/**
 * Drift check (FR6): regenerate the manifest from the resolved probe code and
 * byte-compare against the committed probes.yaml. Any drift — a hand edit, a
 * probe change, a feature-set change — is a hard, diff-printing failure.
 */
export async function checkProbeManifestDrift(
  templateDir: string,
  options?: { overrides?: ProbeOverrideInput[]; workspaceRoot?: string },
): Promise<void> {
  const manifestPath = join(templateDir, PROBE_MANIFEST_FILE);
  const regenerated = renderProbeManifest(await generateProbeManifest(templateDir, options));
  if (!(await exists(manifestPath))) {
    throw new CyanError(
      problem(
        'validation',
        'probe_manifest_drift',
        `Missing committed ${PROBE_MANIFEST_FILE} for ${templateDir} — a feature-declaring template must commit ` +
          'its machine-generated probe manifest.',
        { templateDir },
      ),
    );
  }
  const committed = await readText(manifestPath);
  if (committed !== regenerated) {
    const diff = unifiedDiff(committed, regenerated, {
      fromLabel: `${PROBE_MANIFEST_FILE} (committed)`,
      toLabel: `${PROBE_MANIFEST_FILE} (regenerated)`,
    });
    throw new CyanError(
      problem(
        'validation',
        'probe_manifest_drift',
        `Committed ${PROBE_MANIFEST_FILE} has drifted from the resolved probe code in ${templateDir} — ` +
          `regenerate it.\n${diff}`,
        { templateDir, diff },
      ),
    );
  }
}
