name: package-release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  packages:
    uses: ./.github/workflows/reusable-package-release.yaml
    secrets: inherit
